### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'  lineDetector.<Field at offset 0x00000008> was null.

### ISSUE THREAD

**Issue by Jorgegarcia197** [microsoft/Microsoft-Rocket-Video-Analytics-Platform#10]
Windows 10 
CUDA 8.0 
cuDNN 9.1 
nvidia driver 442.19
.NET Core 2.2.102

I've tried to implement this repository but I get the next error while running the code. It does initialize and creates the output folders but does not start the footage processing. 

Tried to debug it and run it in different CPU settings but did not manage to make it work

Hope you can help me 

![Issue](https://user-images.githubusercontent.com/46676143/73984380-20f45d00-48fe-11ea-9af8-00fbd1901df3.PNG)

**Comment by ycshu086** [comment]
Hi, can you please check if the line configuration file was in place (Microsoft-Rocket-Video-Analytics-Platform\cfg\), and it was specified in the debug arguments? The app should be running out of the box.

**Comment by Jorgegarcia197** [comment]
Yes, I am running the sample.txt file as the config file that is in the original repo and did the setup in the debug properties for the expected config line. 

![image](https://user-images.githubusercontent.com/46676143/74288102-2d5b2a00-4cf1-11ea-9c7e-fa452584f442.png)


![debug confing](https://user-images.githubusercontent.com/46676143/74287964-dce3cc80-4cf0-11ea-9e8a-a7c152f96558.PNG)

**Comment by ycshu086** [comment]
Can you check if the return of `LineSets.readLineSet_LineDetector_FromTxtFile` (line 29 in LineDetector\Detector.cs) is null? If so, can you add breakpoints in LineSets.cs to check how it happened?

**Comment by Jorgegarcia197** [comment]
I found the issue by debugging throughout the Detector.cs . 
![Main cs issue](https://user-images.githubusercontent.com/46676143/74468651-c6f51980-4e60-11ea-9c55-a0ae6722a185.PNG)
During the initialization process, the variable lineFile reads the config file and assigns the path to it in order to read it. 
![image](https://user-images.githubusercontent.com/46676143/74468838-23583900-4e61-11ea-9dee-698eb9fb2cb3.png)
Indeed the line29 of Detector.cs does return null.

![Root_issue](https://user-images.githubusercontent.com/46676143/74468939-4f73ba00-4e61-11ea-9a1e-9bc83ea35780.png)

It was until I added the breakpoints to the LineSets.cs file that I figured out why it is null. It is because it parses the fileName variable established before (In this case ("..\\..\\..\\..\\..\\..\\cfg\\sample.txt")) but when it tries to read the file somehow is calling another path (in this case ("..\..\..\..\Microsoft-Rocket-Video-Analytics-Platform\**src**\cfg\sample.txt)) and that path does not coincides where the sample.txt file is.

**Comment by ycshu086** [comment]
Your debug platform is set to x64, instead of Any CPU, which makes bin\Debug\netcoreappx.x\x64 the current folder. Hence, ..\..\..\..\..\..\cfg\sample.txt ended up pointing to \src\cfg\. You can either change the debug platform back to Any CPU, or adding another ..\ to paths of videoUrl and lineFile in Program.cs.
