### ISSUE TITLE
Defining multiple lines

### ISSUE THREAD

**Issue by mahshidgh** [microsoft/Microsoft-Rocket-Video-Analytics-Platform#11]
Hello, I'm trying to define multiple lines in the configuration file but, it seems like it only reads the first line and if I define more that one line it throws an out of index error, like below(I was wondering shouldn't 0*5 be i*7 or something like that because each line has 7 arguments and i is keeping track of each line?) I also attached the conf file that I'm using in which I have defined two lines.
![image](https://user-images.githubusercontent.com/36775869/77774883-24fd4b00-7022-11ea-9ac1-c5d8309ffe9e.png)
Here is the conf file I'm using
![image](https://user-images.githubusercontent.com/36775869/77774987-4bbb8180-7022-11ea-9446-1bb83671554f.png)
Would you please help me with how I can define multiple lines?

**Comment by ycshu086** [comment]
The question was answered offline. Pasting the solution below and closing the issue. 

the second line should be,
b_line  **1**      934     379    1031       347         0.3
 
The **marked field** is not the id of the line, but rather the _number_ of lines. In Rocket, you can use two lines to trigger a count, say, that an object has to cross line 1 and line 2 within a min and max frame gap of G. e.g., 
b_line   2              X11         Y11         X12         Y12         Overlap_L1         X21         Y21         X22         Y22         Overlap_L2                30           100

The above example shows that if an object crosses L1 and then L2 within 30 to 100 frames, a trigger will be raised. This is an advanced feature which you can ignore if you only want to use one line for each count.
