### ISSUE TITLE
Unable to download the Microsoft-Rocket-Video-Analytics-Platform-opencv_world340.dll

### ISSUE THREAD

**Issue by JpKuo24** [microsoft/Microsoft-Rocket-Video-Analytics-Platform#15]
Hi there,
When I build the rocket on Windows and try to run the Config.bat, I find I cannot download opencv binary files
I list them as below for your reference, it seems that I do not have the permission to get this file. How to deal with this staff?

(base) C:\Users\95492\Downloads\Microsoft-Rocket-Video-Analytics-Platform-master>powershell -Command "(New-Object Net.WebClient).DownloadFile('https://aka.ms/Microsoft-Rocket-Video-Analytics-Platform-opencv_world340.dll', './src/VAP/YoloWrapper/Dependencies/opencv_world340.dll')"
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At line:1 char:1
+ (New-Object Net.WebClient).DownloadFile('https://aka.ms/Microsoft-Roc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

(base) C:\Users\95492\Downloads\Microsoft-Rocket-Video-Analytics-Platform-master>powershell -Command "(New-Object Net.WebClient).DownloadFile('https://aka.ms/Microsoft-Rocket-Video-Analytics-Platform-opencv_world340d.dll', './src/VAP/YoloWrapper/Dependencies/opencv_world340d.dll')"
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At line:1 char:1
+ (New-Object Net.WebClient).DownloadFile('https://aka.ms/Microsoft-Roc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by ycshu086** [comment]
Thank you for reporting the issue. It's been fixed.
