### ISSUE TITLE
Error : Unable to load DLL 'x64\yolo_cpp_dll_gpu_lt.dll' 

### ISSUE THREAD

**Issue by Mitra-M** [microsoft/Microsoft-Rocket-Video-Analytics-Platform#9]
Win 10 1803
VS 2017   + ( C++ 2015.3 v140 toolset)
CUDA 9.1  , cuDNN 8.0  ,  Nvidia driver 441.22
 .NET Core 2.2

I compiled this great project without any error , but I get this error when running :

> System.DllNotFoundException: 'Unable to load DLL 'x64\yolo_cpp_dll_gpu_lt.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

tried Debug/Release  , AnyCPU / x64

Please look at this image :

![Error](https://user-images.githubusercontent.com/17668160/72827097-00a27e00-3c2f-11ea-8d16-ed122e9b2dd4.png)

**Comment by ycshu086** [comment]
Hi, can you try again with CUDA 8.0? It is needed to run DarkNet models like YOLOv3. CUDA 9.1 only works for TensorFlow model (e.g., pipeline 2, 5). [https://github.com/microsoft/Microsoft-Rocket-Video-Analytics-Platform#setup-on-windows](url)

**Comment by Mitra-M** [comment]
Hi ycshu,

The problem solved by using  CUDA 8.0 + DarkNet models , thank you so much.
